project:
  type: book
  output-dir: docs

book:
  title: "Ramble On's Progress Journal"
  repo-url: https://github.com/pjournal/mef06g-ramble-on
  chapters:
    - index.qmd
    - assignment1.qmd
    - Preprocessing.qmd
    - Exploratory Data Analysis.qmd
    - Shinyapps.qmd
    - The Final Report.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

